project:
  type: website
  output-dir: docs

website:
  title: "My Quarto Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: labs.qmd
        text: Labs
      - href: projects.qmd
        text: Projects
      - href: presentation.qmd
        text: Presentations

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

# 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